# Generated by Django 5.0.4 on 2024-04-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.estadopedido'),
        ),
    ]
