# Generated by Django 5.0.4 on 2024-06-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('3', 'FACTURACION'), ('2', 'CONFECCION'), ('1', 'RECEPCION'), ('5', 'ENTREGADO'), ('4', 'TERMINADO')], max_length=2),
        ),
    ]
