# Generated by Django 5.0.4 on 2024-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pasos_sectores_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('5', 'ENTREGADO'), ('2', 'CONFECCION'), ('1', 'RECEPCION'), ('4', 'TERMINADO'), ('3', 'FACTURACION')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Pasos',
        ),
    ]
