# Generated by Django 5.0.4 on 2024-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_user_creater_alter_sectores_paso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='user_creater',
            new_name='user_creator',
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('4', 'TERMINADO'), ('1', 'RECEPCION'), ('3', 'FACTURACION'), ('5', 'ENTREGADO'), ('2', 'CONFECCION')], max_length=2),
        ),
    ]
