# Generated by Django 5.0.4 on 2024-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_sectores_paso_delete_pasos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('3', 'FACTURACION'), ('4', 'TERMINADO'), ('1', 'RECEPCION'), ('5', 'ENTREGADO'), ('2', 'CONFECCION')], max_length=2),
        ),
    ]
