# Generated by Django 5.0.4 on 2024-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('2', 'CONFECCION'), ('4', 'TERMINADO'), ('1', 'RECEPCION'), ('3', 'FACTURACION'), ('5', 'ENTREGADO')], max_length=2),
        ),
    ]
