# Generated by Django 5.0.4 on 2024-07-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_rename_user_creater_pedido_user_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='user_creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('2', 'CONFECCION'), ('1', 'RECEPCION'), ('4', 'TERMINADO'), ('5', 'ENTREGADO'), ('3', 'FACTURACION')], max_length=2),
        ),
    ]
