# Generated by Django 5.0.4 on 2024-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_user_creator_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('3', 'FACTURACION'), ('4', 'TERMINADO'), ('5', 'ENTREGADO'), ('2', 'CONFECCION'), ('1', 'RECEPCION')], max_length=2),
        ),
    ]
