# Generated by Django 5.0.4 on 2024-04-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('5', 'ENTREGADO'), ('1', 'RECEPCION'), ('2', 'CONFECCION'), ('3', 'FACTURACION'), ('4', 'TERMINADO')], max_length=2),
        ),
    ]
