# Generated by Django 5.0.4 on 2024-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('5', 'ENTREGADO'), ('3', 'FACTURACION'), ('4', 'TERMINADO'), ('2', 'CONFECCION'), ('1', 'RECEPCION')], max_length=2),
        ),
    ]
