# Generated by Django 5.0.4 on 2024-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_sectores_paso'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoProducto',
            new_name='PedidoItem',
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('3', 'FACTURACION'), ('5', 'ENTREGADO'), ('4', 'TERMINADO'), ('2', 'CONFECCION'), ('1', 'RECEPCION')], max_length=2),
        ),
    ]
