# Generated by Django 5.0.4 on 2024-07-08 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_rename_pedidoproducto_pedidoitem_alter_sectores_paso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('2', 'CONFECCION'), ('1', 'RECEPCION'), ('3', 'FACTURACION'), ('4', 'TERMINADO'), ('5', 'ENTREGADO')], max_length=2),
        ),
    ]
