# Generated by Django 5.0.4 on 2024-07-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedidoitem_precio_unitario_alter_pedido_user_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('1', 'RECEPCION'), ('3', 'FACTURACION'), ('2', 'CONFECCION'), ('5', 'ENTREGADO'), ('4', 'TERMINADO')], max_length=2),
        ),
    ]
