# Generated by Django 5.0.4 on 2024-08-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedidoitem_pedido_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('5', 'ENTREGADO'), ('1', 'RECEPCION'), ('2', 'CONFECCION'), ('4', 'TERMINADO'), ('3', 'FACTURACION')], max_length=2),
        ),
    ]
