# Generated by Django 5.0.4 on 2024-08-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_sectores_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('4', 'TERMINADO'), ('2', 'CONFECCION'), ('3', 'FACTURACION'), ('1', 'RECEPCION'), ('5', 'ENTREGADO')], max_length=2),
        ),
    ]
