# Generated by Django 5.0.4 on 2024-08-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_sectores_paso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='estadopedido',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('2', 'CONFECCION'), ('3', 'FACTURACION'), ('4', 'TERMINADO'), ('5', 'ENTREGADO'), ('1', 'RECEPCION')], max_length=2),
        ),
    ]
