# Generated by Django 5.0.4 on 2024-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_remove_pedido_estado_estadopedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('1', 'RECEPCION'), ('2', 'CONFECCION'), ('3', 'FACTURACION'), ('4', 'TERMINADO'), ('5', 'ENTREGADO')], max_length=2),
        ),
    ]
