# Generated by Django 5.0.4 on 2024-08-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_sectores_paso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('4', 'TERMINADO'), ('2', 'CONFECCION'), ('1', 'RECEPCION'), ('5', 'ENTREGADO'), ('3', 'FACTURACION')], max_length=2),
        ),
    ]
