# Generated by Django 5.0.4 on 2024-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_remove_pedidoitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='paso',
            field=models.CharField(choices=[('3', 'FACTURACION'), ('1', 'RECEPCION'), ('2', 'CONFECCION'), ('5', 'ENTREGADO'), ('4', 'TERMINADO')], max_length=2),
        ),
    ]
