# Generated by Django 5.0.4 on 2024-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='escribano',
            field=models.BooleanField(default=False),
        ),
    ]
