# Generated by Django 5.0.4 on 2024-04-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_mañana', models.IntegerField()),
                ('limite_tarde', models.IntegerField()),
                ('dias_habiles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('notarial', models.BooleanField(default=False)),
                ('entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.entrega')),
            ],
        ),
    ]
